# Site settings
title: Eagle
email: hchen9@ebay.com
description: Secure Hadoop in Real Time

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://goeagle.io" # the base hostname & protocol for your site
twitter_username: eagle
github_username:  eagle

# Build settings
markdown: kramdown

documentations:
  - category: Overview
    links:
      - title: What is Eagle
        url: /docs/index.html
      - title: Use Cases
        url: /docs/usecase.html        
  - category: Installation
    links:
      - title: Pre-requisites
        url: /docs/installation.html
      - title: Deploying Eagle
        url: /docs/install/ambari-plugin.html
  - category: Policy Management
    links:
      - title: HDFS Policies
        url: /docs/tutorial/how-to-define-eagle-policy.html
      - title: Hive Policies
        url: /docs/tutorial/how-to-use-rest-api.html
  - category: User Profiles
    links:
      - title: Offline Training
        url: /docs/tutorial/how-to-define-eagle-policy.html
      - title: Online Processing
        url: /docs/tutorial/how-to-use-rest-api.html
  - category: Data Classification
    links:
      - title: HDFS
        url: /docs/tutorial/how-to-define-eagle-policy.html
      - title: Hive
        url: /docs/tutorial/how-to-use-rest-api.html