# Site settings
title: Eagle
email: cn.haochen@gmail.com
description: Secure Hadoop in Real Time

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://goeagle.io" # the base hostname & protocol for your site
twitter_username: eagle
github_username:  eagle

# Build settings
markdown: kramdown

documentations:
  - category: Overview
    links:
      - title: What is Eagle
        url: /docs/index.html
      - title: Use Cases
        url: /docs/usecase.html        
  - category: Installation
    links:
      - title: Deploy Eagle in Sandbox
        url: /docs/deployment-in-sandbox.html
      - title: Deploy Eagle in the Production
        url: /docs/deployment-in-production.html
      - title: Stream Log Data into Kafka
        url: /docs/import-hdfs-auditLog.html
      - title: Install Eagle Ambari Plugin
        url: /docs/ambari-plugin-install.html
      - title: Frequently Asked Questions
        url: /docs/FAQ.html
  - category: Policy Management
    links:
      - title: HDFS Policies
        url: /docs/hdfs-policy.html
      - title: Hive Policies
        url: /docs/hive-policy.html
  - category: User Profiles
    links:
      - title: Offline Training
        url: /docs/offline-user-profiles.html
      - title: Online Processing
        url: /docs/online-user-profiles.html
  - category: Data Classification
    links:
      - title: Site Management
        url: /docs/setup.html
      - title: Classfication
        url: /docs/hdfs-classify.html