# Site settings
title: Eagle
email: hchen9@ebay.com
description: Secure Hadoop in Real Time

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://goeagle.io" # the base hostname & protocol for your site
twitter_username: eagle
github_username:  eagle

# Build settings
markdown: kramdown

documentations:
  - category: Overview
    links:
      - title: What is Eagle
        url: /docs/index.html
      - title: Use Cases
        url: /docs/usecase.html        
  - category: Installation
    links:
      - title: Deploy Eagle in Sandbox
        url: /docs/deploymentInSandbox.html
      - title: Deploy Eagle in the Production
        url: /docs/deploymentInProduction.html
      - title: Import log data into Kafka
        url: /docs/importHDFSAuditLog.html
      - title: Install Eagle Ambari Plugin
        url: /docs/ambariPluginInstall.html
  - category: Policy Management
    links:
      - title: HDFS Policies
        url: /docs/hdfspolicy.html
      - title: Hive Policies
        url: /docs/hivepolicy.html
  - category: User Profiles
    links:
      - title: Offline Training
        url: /docs/offlineUserProfiles.html
      - title: Online Processing
        url: /docs/onlineUserProfiles.html
  - category: Data Classification
    links:
      - title: HDFS
        url: /docs/hdfsclassify.html
      - title: Hive
        url: /docs/hiveclassify.html